columns:
  - Destination Port: int64
  - Flow Duration: int64
  - Total Fwd Packets: int64
  - Total Backward Packets: int64
  - Total Length of Fwd Packets: float64
  - Total Length of Bwd Packets: float64
  - Flow Bytes/s: float64
  - Flow Packets/s: float64
  - Fwd Packet Length Mean: float64
  - Bwd Packet Length Mean: float64
  - SYN Flag Count: int64
  - ACK Flag Count: int64
  - Init_Win_bytes_forward: int64
  - Init_Win_bytes_backward: int64
  - Label: int64

numerical_columns:
  - Destination Port
  - Flow Duration
  - Total Fwd Packets
  - Total Backward Packets
  - Total Length of Fwd Packets
  - Total Length of Bwd Packets
  - Flow Bytes/s
  - Flow Packets/s
  - Fwd Packet Length Mean
  - Bwd Packet Length Mean
  - SYN Flag Count
  - ACK Flag Count
  - Init_Win_bytes_forward
  - Init_Win_bytes_backward
  - Label
